server:
  port: 8088

spring:
  application:
    name: irrigation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/FarmEasy}
    username: ${SPRING_DATASOURCE_USERNAME:anandmohan}
    password: ${SPRING_DATASOURCE_PASSWORD:FarmEasy}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: irrigation

management:
  endpoints:
    web:
      exposure:
        include: health,info
